name: Question
description: Ask a question
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Before opening an issue with a question:
        - please read the [FAQ](https://weechat.org/doc/weechat/faq) and [documentation](https://weechat.org/doc/weechat/)
        - please ask on #weechat channel (on server irc.libera.chat).

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Your question.
    validations:
      required: true
